### ISSUE TITLE
Remove underlines from links

### ISSUE THREAD

**Issue by VivekKumarApps** [fobid/linkable-text-android#19]
Hello,
Can we remove underline from the link text?

Please tell me how we can remove.

**Comment by fobidlim** [comment]
Hello, @VivekKumarApps 

I prepare for next version to remove underline as options.
Please wait for next update.

After updated, I will let you know through the comment.
Thank you.

**Comment by fobidlim** [comment]
v0.1.3 Updated.

You can find changelog on [CHANGELOG](https://github.com/fobid/linkable-text-android/blob/master/CHANGELOG.md).
And please check [README](https://github.com/fobid/linkable-text-android#attributes) again.

Thank you.
